Resources:
  Ec2Instance: #Logical ID
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0ad99772 # Amazon Linux AMI in Oregon
      Tags:
        - Key: Name
          Value: A simple example

# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-instance.html
